### PR TITLE
Improve TLE data presentation

### PR DESCRIPTION
**Pull request by tomaszmrugalski**
Hey, @fivitti, I'm working on better TLE visualization. One thing I'm struggling with is the bootstrap classes. The current TLE presentation is broken. We don't preserve spaces, so if you try to copy and use it, you'll get errors).

Here's what I came up with:

tle

The first is a basic `<pre>` tag that shows plain TLE data. That's boring, but at least it lets users copy the data. The second is more interesting, as each element is color-coded differently and you can hover your mouse over it to get an explanation. It's all cool, but I've encountered the problem.

I've tried to define classes in bootstrap-custom.css:
```css
.tle1 span { white-space: pre; color: green }
.tle2 span { white-space: pre; color: blue }
.tle3 span { white-space: pre; color: black }
.tle4 span { white-space: pre; color: orange }
```

and then use it:
```html
<code class="tle1">
    <span class="tle1">01 2  3   4    X</span>
</code>
```
Sadly, it doesn't work. This, however, works fine:
```html
<code>
    <span style="color: green; white-space: pre;">01 2  3   4    X</span>
</code>
```

Any idea why?

### CODE REVIEW

**Comment by tomaszmrugalski** [comment]
The code is now ready for review. This is how it looks like. The next step (in a separate PR) will be to present orbital data in more useful manner (apogee, perigee, inclination, altitude, type of an orbit, etc.). Maybe sub-satellite points for AOS, TCA and LOS?

**Review by fivitti — COMMENTED** [review]
I change a little your code. I wrap the ```code``` tag with ```pre```. It is recommended for blocks. The single ```code``` tag is for inline (in text) use. It allow to use built-in Bootstrap styles without coping them.

I notice that you set a fixed width of TLE block. It breaks a view on mobile devices - TLE has full width, but other elements are small. I used ```overflow``` property to fix it.

If you don't accept my changes then feel free to revert my commit.

**Comment by fivitti** [comment]
One tip - tags as ```<b>```, ```<i>``` or ```<br>``` are for simple text documents. For HTML pages you should to use the CSS properties as ```font-weight```, ```font-decoration``` and ```display```.

**Comment by tomaszmrugalski** [comment]
Looks great! thanks.

**Pull request merged**
